version: "3.7"

services:
  oracle:
    # Make sure the image is built from https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance
    image: oracle/database:21.3.0-xe
    ports:
      - 1521:1521
      - 5500:5500
    volumes:
      - ./.oracle/oradata:/opt/oracle/oradata
      - ./.oracle/scripts/setup:/opt/oracle/scripts/setup
      - ./.oracle/scripts/startup:/opt/oracle/scripts/startup

    environment:
      - ORACLE_PWD=password123
      - ORACLE_CHARACTERSET=AL32UTF8
