version: "3.7"
services:
  soda-core-vertica:
    image: vertica/vertica-ce:12.0.2-0
    ports:
      - "5433:5433"
    deploy:
      mode: global
    volumes:
      - type: volume
        source: vertica-data
        target: /data
    environment:
      APP_DB_USER: "dbadmin"
      APP_DB_PASSWORD: "password"
      TZ: "UTC"
      VERTICA_MEMDEBUG: 2 # https://forum.vertica.com/discussion/242629/support-apple-silicon-m1-for-docker-vertica-ce
    command: >
      bash -c "
        export APP_DB_PASSWORD="password" &&
        rm -rf /home/dbadmin/docker/ &&
        /opt/vertica/bin/admintools -t create_db --database=vmart --password=$APP_DB_PASSWORD --hosts=localhost
      "
volumes:
  vertica-data:
